// This file is automatically generated.
// Please do not change this file!
// biome-ignore lint/complexity/noBannedTypes: <explanation>
type CssExports = {};
export const cssExports: CssExports;
export default cssExports;
